[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/newsletter"]

[project]
name = "newsletter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "diskcache>=5.6.3",
    "ipykernel>=7.1.0",
    "marimo>=0.19.4",
    "matplotlib>=3.10.8",
    "polars>=1.37.1;platform_system!='Windows'",
    "polars[timezone]>=1.37.1;platform_system=='Windows'",
    "pydantic-ai>=1.43.0",
    "pytest>=9.0.2",
    "pytest-asyncio>=1.3.0",
    "python-dotenv>=1.2.1",
]

[tool.mypy]
explicit_package_bases=true
